[package]
name = "rust-raiden"
version = "0.1.0"
authors = ["Rakan Alhneiti <rakan.alhneiti@gmail.com>"]
edition = "2018"

[dependencies]
web3 = { git = "https://github.com/tomusdrw/rust-web3" }

[[bin]]
path = "raiden/main.rs"
name = "raiden"
