[package]
name = "raiden"
version = "0.1.0"
authors = ["Rakan Alhneiti <rakan.alhneiti@gmail.com>"]
edition = "2018"

[dependencies]
web3 = { git = "https://github.com/tomusdrw/rust-web3" }
rusqlite = "0.20.0"
serde = "1.0.101"
serde_json = "1.0.40"
hex = "0.4.0"

[[bin]]
path = "raiden/main.rs"
name = "raiden"

[lib]
path = "raiden/lib.rs"